### ISSUE TITLE
Failure on pull requests with "Error: Resource not accessible by integration"

### ISSUE THREAD

**Issue by gatecat** [hasura/comment-progress#9]
Hi!

We are trying to use `comment-progress` to provide docs preview URLs in pull requests. However, when that PR comes from another repo where the submitter doesn't have permissions, it fails with "Error: Resource not accessible by integration": https://github.com/lip6/coriolis/actions/runs/7486683734/job/20377534428?pr=108#step:2:20

Do you have any suggestions how it might be possible to make this work?

**Comment by wu-lee** [comment]
I just ran into something similar... 

The error references this documentation:  https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment

That says:

> The fine-grained token must have at least one of the following permission sets:
> 
>     "Issues" repository permissions (write)
>     "Pull requests" repository permissions (write)

Which basically means you need to add the right permissions:

```
jobs:
  deploy:
    # ...
    permissions:
      contents: write
      # I needed to add these two permissions
      issues: write
      pull-requests: write
```

I'm not certain if this resolves the OP's case where the submitter doesn't have permissions to the repo in question, however.
